### ISSUE TITLE
Screen Flickers on IE10 and IE Edge(11)

### ISSUE THREAD

**Issue by theAngryCoder** [noahcooper/jQuery.thermometer#2]
I am trying to use the plugin on IE10 and IE11(Edge), the image doesn't show up. The screen turns black and starts to flicker.

**Comment by noahcooper** [comment]
Do you have a link to a page I can review? Testing http://noahcooper.github.io/jQuery.thermometer/ in IE10 and IE11 shows no problems.

**Comment by theAngryCoder** [comment]
@noahcooper sorry for that, I intended to type it on a different page and ended up typing it here. I had too many tabs open at that time.
